### ISSUE TITLE
Problem with upload field

### ISSUE THREAD

**Issue by rysi3k** [AlainCouthures/xsltforms#5]
Hello,
I have that field:
```xml
<xf:upload
    _bind="ID14" ref="wnio:ID14">
    <xf:filename ref="../@nazwaPliku"/>
    <xf:label>
    <span/>
    </xf:label>
</xf:upload>
```
XSLTForms renders that field propertly but after select file there there are alert with "Error". I have fixed this with modifing `XsltForms_binding.prototype.evaluate` to that:
```javascript
XsltForms_binding.prototype.evaluate = function() {
	return this.bind_evaluate.apply(this, arguments);
};
```
I don't know it's ok? it's bug or I missed something?

Regards

**Comment by AlainCouthures** [comment]
Hello,
There are still some "meaningless" method names in XSLTForms due to its ancestor project and it is difficult to read source lines and immediately recognize the class of an object.

Being the worse case, the evaluate method had to be renamed and it was just maintained to catch missed replacements with an alert. Could you please use a browser debugging, add a breakpoint for the alert instruction then get corresponding source line for the call to be renamed?

Thank you in advance!

**Comment by rysi3k** [comment]
This call is in line 12437 http://scr.hu/1b8d/pqw9z in XsltForms_upload.prototype.change
i think the same call is in XsltForms_upload.prototype.directclick in 12330

**Comment by AlainCouthures** [comment]
This has be fixed in latest commit.

Thanks!
